server:
    port: 8089
    ssl:
        key-store: classpath:yenroc.pfx
        key-store-password: xU6Etdj7
spring:
    application:
        name: springboot-project-demo
    redis:
        host: 134.175.91.16
