server:
    port: 8089
spring:
    application:
        name: springboot-project-demo
    redis:
        host: 134.175.91.16
    servlet:
        multipart:
            max-file-size: 1024MB
            max-request-size: 4096MB
    
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000