server:
    port: 8089
    ssl:
        key-store: classpath:yenroc.pfx
        key-store-password: xU6Etdj7
spring:
    application:
        name: springboot-project-demo
    redis:
        host: 134.175.91.16
    thymeleaf:
        #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
        mode: HTML
        #编码 可不用配置
        encoding: UTF-8
        #开发配置为false,避免修改模板还要重启服务器
        cache: false
        #配置模板路径，默认是templates，可以不用配置
        prefix: classpath:/templates/